# render.yaml
services:
  - type: web
    name: balwinder-portfolio
    env: static
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
